export default function () {
  return {
    data: [
      {
        id: 1,
        title: 'Продаю: корова, телёнок | для разведения',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg', 'cat.jpg', 'cat.jpg', 'cat.jpg'],
        amount: 234567,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
      {
        id: 2,
        title: 'Продаю быка на забив',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg'],
        amount: 1120000,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
      {
        id: 3,
        title: 'Продаю корову 3 года',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg'],
        amount: 120000,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
      {
        id: 4,
        title: 'Продаю корову, 5 лет, 20л',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg'],
        amount: 120000,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
      {
        id: 5,
        title: 'Продаю: корова, телёнок | для разведения',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg'],
        amount: 120000,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
      {
        id: 6,
        title: 'Продаю: корова, телёнок | для разведения',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg'],
        amount: 120000,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
      {
        id: 7,
        title: 'Продаю: корова, телёнок | для разведения',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg'],
        amount: 120000,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
      {
        id: 8,
        title: 'Продаю: корова, телёнок | для разведения',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg'],
        amount: 120000,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
      {
        id: 9,
        title: 'Продаю: корова, телёнок | для разведения',
        images: ['product-img.jpg', 'tiger.jpg', 'cat.jpg'],
        amount: 120000,
        ccy: 'KGS',
        city: 'Нарын',
        cat: '',
        type: 'Телка',
        breed: 'Бельгийская голубая',
        phone: '0555005500',
        age: 5,
        quantity: 3,
        description: 'Продаю Тёлок на мясо и на разведение. Вес от 120 до 140 кг мясом. Возраст 1 год ЦЕНА 58 ТЫСЯЧ. ПОРОДИСТЫЕ.'
      },
    ]
  }
}
